from .hash_utils import hash_sha256, xor_calculator, bits_converter
from .lamport_ots import LamportOTS
from .merkle import MerkleTree
from .baseline import StatefulHBS

# Test the functions
######### note: these test are generated by AI for functional testing
'''
hash_utils

测：

hash 长度是否正常
XOR 是否正常
bits 是否是 256 位且只包含 0/1

对应你截图里“keygen 正常、基础逻辑正常”的底层支持。

LamportOTS

测：

keygen 是否正常生成
sign 后 verify 能不能通过
错误消息会不会失败
错误签名会不会失败
错误公钥会不会失败

这正好覆盖了你截图里那几项，而且比截图多一项“错公钥失败”。

MerkleTree

测：

root 是否生成
正确 leaf/path 是否通过
wrong leaf / wrong index / wrong path 是否失败
StatefulHBS

测：

baseline sign → verify
wrong message fail
wrong signature fail
wrong path fail
重复使用 keyid 是否报错

这比只测 LamportOTS 更完整，因为你已经实现了 stateful baseline
'''
def test_hash_utils():
    print("Testing hash_utils...")

    # hash_sha256
    h = hash_sha256(b"hello")
    assert isinstance(h, bytes)
    assert len(h) == 32

    # xor_calculator
    x = xor_calculator(b"\x01\x02", b"\x03\x04")
    assert x == b"\x02\x06"

    # bits_converter
    bits = bits_converter(b"hello")
    assert isinstance(bits, list)
    assert len(bits) == 256
    assert all(bit in [0, 1] for bit in bits)

    print("hash_utils passed")


def test_lamport_ots():
    print("Testing LamportOTS...")

    ots = LamportOTS()
    sk, pk = ots.keygen()

    msg = b"hello"
    sig = ots.sign(msg, sk)

    # keygen
    assert isinstance(sk, dict)
    assert isinstance(pk, dict)
    assert "zero" in sk and "one" in sk
    assert "zero" in pk and "one" in pk
    assert len(sk["zero"]) == 256
    assert len(sk["one"]) == 256
    assert len(pk["zero"]) == 256
    assert len(pk["one"]) == 256

    # sign -> verify
    assert ots.verify(msg, sig, pk) is True

    # wrong message should fail
    assert ots.verify(b"wrong", sig, pk) is False

    # wrong signature should fail
    bad_sig = sig.copy()
    bad_sig[0] = b"wrong"
    assert ots.verify(msg, bad_sig, pk) is False

    # wrong public key should fail
    _, pk2 = ots.keygen()
    assert ots.verify(msg, sig, pk2) is False

    print("LamportOTS passed")


def test_merkle():
    print("Testing MerkleTree...")

    leaves = [b"a", b"b", b"c", b"d"]
    tree = MerkleTree(leaves)

    assert isinstance(tree.root, bytes)
    assert len(tree.root) == 32

    # correct leaf should pass
    index = 2
    path = tree.get_auth_path(index)
    assert tree.verify_path(leaves[index], index, path, tree.root) is True

    # wrong leaf should fail
    assert tree.verify_path(b"x", index, path, tree.root) is False

    # wrong index should fail
    assert tree.verify_path(leaves[index], 1, path, tree.root) is False

    # wrong path should fail
    bad_path = path.copy()
    bad_path[0] = b"wrong"
    assert tree.verify_path(leaves[index], index, bad_path, tree.root) is False

    print("MerkleTree passed")


def test_stateful_hbs():
    print("Testing StatefulHBS...")

    hbs = StatefulHBS(total_keys=4)
    msg = b"hello stateful signatures"

    signed = hbs.sign(0, msg)

    # sign -> verify
    assert hbs.verify(msg, signed) is True

    # wrong message should fail
    assert hbs.verify(b"wrong", signed) is False

    # wrong signature should fail
    bad_signed = signed.copy()
    bad_sig = bad_signed["signature"].copy()
    bad_sig[0] = b"wrong"
    bad_signed["signature"] = bad_sig
    assert hbs.verify(msg, bad_signed) is False

    # wrong path should fail
    bad_signed2 = signed.copy()
    bad_path = bad_signed2["path"].copy()
    bad_path[0] = b"wrong"
    bad_signed2["path"] = bad_path
    assert hbs.verify(msg, bad_signed2) is False

    # key reuse should raise error
    try:
        hbs.sign(0, msg)
        assert False, "Expected ValueError for reused keyid"
    except ValueError:
        pass

    print("StatefulHBS passed")


if __name__ == "__main__":
    print("Running core tests...\n")

    test_hash_utils()
    test_lamport_ots()
    test_merkle()
    test_stateful_hbs()

    print("\nAll tests passed.")